[project]
name = "homework-9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.13",
    "pydantic>=2.11.7",
    "tensorflow>=2.19.0",
    "uvicorn>=0.34.3",
]
