[project]
name = "homework-12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "peft>=0.17.0",
    "transformers>=4.55.0",
]
