name: CI_check

on:
  push:

jobs:
  homework_1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Run image # install uv
        uses: astral-sh/setup-uv@v5.4.1

      - name: Install dependencies # install all dependencies
        run: |
          cd homework_1
          uv sync --group test

      - name: Run static analyzis
        run: |
          cd homework_1
          uv run pre-commit run --files *

      - name: Run pytest
        run: |
          cd homework_1
          uv run coverage run -m --source=src pytest tests
          uv run coverage report

  homework_2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Run image # install uv
        uses: astral-sh/setup-uv@v5.4.1

      - name: Install dependencies # install all dependencies
        run: |
          cd homework_2
          uv sync

      - name: Run mypy
        run: |
          cd homework_2
          uv run mypy basic.py intermediate.py

  homework_4:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Run image # install uv
        uses: astral-sh/setup-uv@v5.4.1

      - name: Install dependencies # install all dependencies
        run: |
          cd homework_4
          uv sync --group test

      - name: Run tests
        run: |
          cd homework_4
          uv run pytest test.py
